### ISSUE TITLE
Offline function invoke (cross-project) + helper

### ISSUE THREAD

**Issue by johncmckim** [gertjvr/serverless-docker#10]
# Feature Proposal)
## Description
When running functions locally, as soon as you access the `aws-sdk` all subsequent calls are made to the cloud. The `SERVERLESS_SIMULATE` environment variable as specified in #8 will allow people to avoid this by creating factories that change behaviour when running locally.

For example, if you wanted to use DynamoDB or Memcached you could do the following.

```
if (process.env.SERVERLESS_SIMULATE) {
   return new AWS.DynamoDB({ endpoint: new AWS.Endpoint('http://localhost:8000') });
}
```

But there is no simple way of achieving this for Lambda. This is because there is no registry of what functions exist where on a machine.

I suggest we add a `sls simulate register` command and a `register` lifecycle event to `invoke` and `serve`. The register hook would store the functions + path in a common user file i.e. `~/.serverless-simulate/registry` in the format `{service:name}-{function:name}`.

```
{
  "user-service-addUser": "/Users/john/project/handler"
}
```

We can then create a helper that would access the registry and invoke functions across services.

```
const simulateInvoker = require('serverless-docker/local-invoke')

if (process.env.SERVERLESS_SIMULATE) {
   return simulateInvoker.invoke('user-service-addUser', event);
}
```

*Bonus*
Support setting for where the registry lives

```
custom:
  simulate:
    registryLocation: ./simulate-registry
```

**Comment by nicka** [comment]
@johncmckim Love the idea and initial design/goals!

One thing I noticed:
`"user-service-addUser": "/Users/john/project/handler"` what if the file includes more handlers? Might need some handler prefixing.

**Comment by johncmckim** [comment]
@nicka so the idea is that we'll identify by service name + function name. So the key will be `${serviceName}-${functionName}`.

It does assume that this will be unique across an application (group of services). If we can set where the registry lives that should a reasonable assumption as they should be unique in AWS anyway.

**Comment by nicka** [comment]
@johncmckim Not sure if we're talking about the same thing (or I'm not getting it haha).
I'm talking about multiple handlers within the same Lambda function.

**Comment by johncmckim** [comment]
Oh sorry @nicka  do you mean like `/Users/john/project/index.handler`. Yea. Need to support that which isn't hard.

I'm going to look at using [dynamodb-local](https://www.npmjs.com/package/dynamodb-localhost) for the registry.

**Comment by nicka** [comment]
@johncmckim perfect!!!

**Comment by johncmckim** [comment]
I've ended up using `lowdb` and creating a HTTP endpoint for the registry.
