### ISSUE TITLE
API Gateway request and response templates.

### ISSUE THREAD

**Issue by gertjvr** [gertjvr/serverless-docker#3]
# Feature Proposal
## Description

API Gateway allow you to configure request and response templates, need to finish the lambda integration.

Similar or dependent issues:
- None
## Additional Data
- [mapping template reference](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html)
- [velocity](http://velocity.apache.org/engine/1.7/user-guide.html)

**Comment by johncmckim** [comment]
As discussed @gertjvr I'll look at implementing this and sending a PR 🔜

**Comment by johncmckim** [comment]
I've made a start on this. The request templates work. I just need to get the response templates working.

I'm just using the default request / response mappings. I don't want to replicate the logic to get the config. I'm hopeful that it will be available to serverless plugins soon.
