### ISSUE TITLE
CORS Support

### ISSUE THREAD

**Issue by johncmckim** [gertjvr/serverless-docker#5]
# Feature Proposal
## Description
Automatically create `OPTIONS` endpoint when `cors` is set on the `http` event

**Comment by gertjvr** [comment]
There should be express middleware to add cors support

Quick google revealed https://www.npmjs.com/package/express-cors

**Comment by johncmckim** [comment]
Yep. Using that. Just needed to add the an `OPTIONS` endpoint and change the filtering of endpoints to allow `OPTIONS` if an authorizer is setup. PR will be incoming 🔜

**Comment by johncmckim** [comment]
Closed with #6
